/**
 * Scripted, repeatable proof of the full x402 payment flow against a running
 * MedRail API instance: 402 -> construct+sign a real Algorand payment ->
 * settle via the live GoPlausible facilitator -> 200 + resource. Writes the
 * result (including the real settled transaction ID) to
 * contracts/artifacts/e2e-proof.json so it can be linked from docs/PROOF.md
 * and independently checked on a block explorer.
 *
 * Requires a funded TestNet keypair in PROOF_MNEMONIC (contracts/.env's
 * DEPLOYER_MNEMONIC works once funded, or any other funded TestNet account
 * holding a little TestNet USDC — see docs/DEPLOYMENT.md).
 *
 * Usage:
 *   API_BASE=http://localhost:4021 npx tsx scripts/e2e-proof.ts
 */
import algosdk from "algosdk";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { x402Client, wrapFetchWithPayment, x402HTTPClient } from "@x402/fetch";
import { ExactAvmScheme } from "@x402/avm/exact/client";
import { dotenvLoad } from "./dotenvLoad.js";

const env = dotenvLoad();
const API_BASE = process.env.API_BASE ?? "http://localhost:4021";
const ALGOD_URL = process.env.ALGOD_URL ?? "https://testnet-api.algonode.cloud";
const mnemonic = process.env.PROOF_MNEMONIC ?? env.DEPLOYER_MNEMONIC;

if (!mnemonic) {
  throw new Error("Set PROOF_MNEMONIC (or DEPLOYER_MNEMONIC in contracts/.env) to a funded TestNet account.");
}

const account = algosdk.mnemonicToSecretKey(mnemonic);

function signer() {
  return {
    address: account.addr.toString(),
    async signTransactions(txns: Uint8Array[], indexesToSign?: number[]) {
      const toSign = new Set(indexesToSign ?? txns.map((_, i) => i));
      return txns.map((bytes, i) => {
        if (!toSign.has(i)) return null;
        const txn = algosdk.decodeUnsignedTransaction(bytes);
        return txn.signTxn(account.sk);
      });
    },
  };
}

async function main() {
  console.log(`Proving live payment flow against ${API_BASE} as ${account.addr}`);

  const client = new x402Client();
  client.register("algorand:*", new ExactAvmScheme(signer(), { algodUrl: ALGOD_URL }));
  const fetchWithPayment = wrapFetchWithPayment(fetch, client);
  const httpClient = new x402HTTPClient(client);

  const response = await fetchWithPayment(`${API_BASE}/v1/triage`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ symptoms: "Sudden chest pain and shortness of breath" }),
  });

  const body = await response.json();
  console.log(`\nFinal status: ${response.status}`);
  console.log("Response body:", JSON.stringify(body, null, 2));

  if (response.status !== 200) {
    throw new Error(
      `Payment did not settle (status ${response.status}). Fund ${account.addr} with TestNet USDC ` +
        `(ASA 10458941) and try again — see docs/DEPLOYMENT.md.`,
    );
  }

  const paymentResponse = httpClient.getPaymentSettleResponse((name) => response.headers.get(name)) as {
    transaction?: string;
  } | null;

  console.log("\nSettlement:", JSON.stringify(paymentResponse, null, 2));
  console.log(`\nVerify independently: https://lora.algokit.io/testnet/transaction/${paymentResponse?.transaction}`);

  const outPath = path.resolve(process.cwd(), "..", "contracts", "artifacts", "e2e-proof.json");
  writeFileSync(
    outPath,
    JSON.stringify(
      {
        timestampNote: "generated by api/scripts/e2e-proof.ts",
        payerAddress: account.addr.toString(),
        endpoint: "/v1/triage",
        httpStatus: response.status,
        settledTransaction: paymentResponse?.transaction,
        explorerUrl: `https://lora.algokit.io/testnet/transaction/${paymentResponse?.transaction}`,
        responseBody: body,
      },
      null,
      2,
    ),
  );
  console.log(`\nWrote proof to ${outPath}`);
}

main().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
